name: CI
on: [ push ]
jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - uses: actions/checkout@v2
      - run: go mod vendor
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - uses: actions/checkout@v2

      - run: |
          go get github.com/ory/go-acc
          go-acc --covermode=count -o coverage.out $(go list ./...)

      - uses: jandelgado/gcov2lcov-action@v1.0.2
        with:
          infile: coverage.out
          outfile: coverage.lcov

      - uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
