name: CI
on: [ push ]
jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
        id: go
      - uses: actions/checkout@v2

      - run: go test ./...
